import type { Metadata } from "next"
import { Lato } from "next/font/google"
import "../styles/global.scss"
import Header from "../components/header"
import Footer from "../components/footer"

// export const fetchCache = 'force-no-store';

const lato = Lato({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Trending Car",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
